[project]
name = "virtualfleet-webapp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "fricour", email = "florian@fricour.com" }
]
requires-python = ">=3.11"
dependencies = [
    "brand-yml>=0.2.0",
    "ipyleaflet>=0.20.0",
    "matplotlib>=3.11.1",
    "playwright>=1.62.0",
    "pytest>=9.1.1",
    "ruff>=0.16.3",
    "shiny-validate>=0.1.3",
    "shiny[theme]>=1.5.0",
    "shinywidgets>=0.8.1",
    "virtualfleet>=0.5.1",
]

[project.scripts]
virtualfleet-webapp = "virtualfleet_webapp:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "pytest>=9.1.1",
    "pytest-playwright>=0.9.0",
]
